Merge frontend branch into dev
3dgeo-heidelberg/pytreedb pull request #96
Opened 2022-07-23 15:14 UTC by annachiu7

- Improve map display on search
- Select by map extent gives users more feedback
- Users can now clear selection by map extent using a new button
- Import/Export query updated
- About page updated
- Pretty print JSON feature collection output
- Fix inconsistency when turning results page
- Tooltips added for ambiguous buttons

2022-07-25 12:11 UTC, han16nah requested changes
The language menu is still present on the About page and the Contact page, can you remove this?

2022-07-25 12:11 UTC, han16nah commented on webserver/pytreedb_server/templates/about.html
> +                    <p>pytreedb was developed in the SYSSIFOSS project by the 3DGeo Research Group of Heidelberg University and the Institute of Geography and Geoecology (IFGG) of Karlsruhe Institute
Please remove one of the dashes

2022-07-25 12:11 UTC, han16nah commented on webserver/pytreedb_server/templates/about.html
> +                    <p>If you are in possession of laser scanning data of trees and are able to fulfil the minimal requirements of the GeoJSON shown above, we welcome you to contribute your data to t
Please change "Checkout out" to "Check out"

2022-07-25 13:29 UTC, han16nah requested changes
in `templates\index.html`, L 82, please change the download link to https://github.com/3dgeo-heidelberg/pytreedb/raw/main/data/test/geojsons.zip (we still have the old heibox link there, which is invalid by now).

Other wise, I can approve the PR :)

2022-07-25 13:29 UTC, han16nah commented on webserver/pytreedb_server/templates/about.html
> +                    <p>If you are in possession of laser scanning data of trees and are able to fulfil the minimal requirements of the GeoJSON shown above, we welcome you to contribute your data to t
I think "Check out" needs a space in between.

2022-08-01 08:59 UTC, annachiu7 commented
@han16nah Can you approve the PR now? :)

2022-08-01 10:10 UTC, han16nah approved these changes

2022-08-01 10:10 UTC, han16nah commented
> @han16nah Can you approve the PR now? :)

yes!

2022-08-01 12:14 UTC, merged